steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.ui
      - -t
      - ${_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: us-central1-docker.pkg.dev/ulbrich-app/ulbrich-containers/ui:dev

options:
  logging: CLOUD_LOGGING_ONLY
